# Application name
spring.application.name=Tienda_Suma

# Server configuration
server.port=8038

# MySQL Configuration - CORREGIDO
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_tiendasuma?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=IN5BM
spring.datasource.password=-mondoM5a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.brandonorellana=DEBUG

# Permitir sobrescribir beans si es necesario
spring.main.allow-bean-definition-overriding=true